
# Valores usados em outras classes, para nao ter "número mágico"


MIN_VERTICE_LIXO = 5
MAX_VERTICE_LIXO = 15

MAX_CAMINHAO_CARGA = 20
MIN_CAMINHAO_FUNCIONARIOS = 3
MAX_CAMINHAO_FUNCIONARIOS = 5
MAX_CAMINHAO_COMPRESSAO = 3


QTD_CARROCINHA = 3
MAX_CARROCINHA_CARGA = 5